"""empty message

Revision ID: 8272a5a8d3c3
Revises: 01e049afee1c
Create Date: 2025-07-18 14:29:51.997618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8272a5a8d3c3'
down_revision: Union[str, None] = '01e049afee1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_by_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_by_email')
    # ### end Alembic commands ###
